---
title: "Attempted fits to Hypotheses"
author: "Pi Nuessle and Judith Racusin"
date: '2023-12-18'
output: word_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(plotly)
library(tidyr)
# library("scatterplot3d")
# library(randomForest)
library(e1071)
library(misc3d)
library(plot3D)
library(scatterplot3d)
library(rgl)
library(data.table)
library(caret)
library(rfUtilities)
library(readr)
library(scales)
library(ggplot2)
library(ggfortify)
library(colorspace)
# library(dplyr)
# library(Peacock.test)
# library(tidyverse)
set.seed(1729)
### SET YOUR FILEPATH
path <- paste(getwd(), "/official github/", sep="")
```

```{r defining the special bursts, echo=FALSE}
Collapsars = c(050416461.0, 50525002.0, 050824966.0, 060218148.0, 060729800.0, 060904104.0, 070419447.0, 071025172.0, 071112772.0, 080319258.0, 081007224.0, 090618353.0, 091127976.0, 100316531.0, 100418882.0, 101219686.0, 101225776.0, 111209300.0, 111211928.0, 111228656.0, 120422300.0, 120714888.0, 120729455.0, 130215063.0, 130427324.0, 130702003.0, 130831544.0, 140206303.0, 140606133.0, 150818483.0, 161219783.0, 161228552.0, 171010792.0, 171205306.0, 180720598.0, 180728728.0, 190114872.0, 190829830.0, 200826187.0, 210210083.0, 211023545.0, 221009553.0, 200826187.0, 150210935.0)
Mergers=c(070809807.0, 130603659.0, 150101641.0, 160624477.0, 160821936.0, 170817528.0, 200522487.0, 060614530.0, 111005336.0, 120304248.0, 211211549.0, 230307655.0, 050509166.0, 050709942.0, 051210240.0, 070714207.0, 071227842.0, 080503518.0, 080905499.0, 090515198.0, 160303454.0)
```

This chunk is needed to create the training set for the classifier. I believe it also creates a version of the data that's paired up with the names.
```{r Goldstein 2.0, echo=FALSE}
Goldstein_S2_Data <- read_excel(file.path(path, "Goldstein_Sample_2_Data.xlsx"), col_types = c("skip", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")) [-c(3), ]
#don't import stuff we won't need right now
par(mar=c(5,5,5,5))
collapsar_mask=Goldstein_S2_Data$Name %in% Collapsars
merger_mask=Goldstein_S2_Data$Name %in% Mergers
Goldstein_S2_collapsars=Goldstein_S2_Data[collapsar_mask, ]
Goldstein_S2_mergers=Goldstein_S2_Data[merger_mask, ]
Goldstein_S2_unknown=Goldstein_S2_Data[!c(collapsar_mask+merger_mask), ]
long_mask=which(Goldstein_S2_unknown$t90>4.2)
short_mask=which(Goldstein_S2_unknown$t90<=4.2)
Goldstein_S2_Long=Goldstein_S2_unknown[long_mask, ]
Goldstein_S2_Short=Goldstein_S2_unknown[short_mask, ]
# plot(Goldstein_S2_Long$t90, Goldstein_S2_Long$`Peak E. over Flue.`, pch=20, ylab=expression(E[p]/S[prompt]~' 10kev-10MeV ('~erg ~ cm^{2} ~ erg^{-1} ~ ', GBM)'), xlab='t90 (s, GBM)', log="xy", xlim=c(1e-2, 1e3))
# points(Goldstein_S2_Short$t90, Goldstein_S2_Short$`Peak E. over Flue.`, pch=20, col='grey')
# points(Goldstein_S2_mergers$t90, Goldstein_S2_mergers$`Peak E. over Flue.`, pch=4, col='red')
# points(Goldstein_S2_collapsars$t90, Goldstein_S2_collapsars$`Peak E. over Flue.`, pch=8, col='blue')
# legend("topleft",
#        legend = c('Unknown Long', 'Unknown Short', "Mergers", 'Collapsars'),
#        col = c('black', 'grey', 'red', 'blue'),
#        pch = c(20, 20, 4, 8))
ggplot(Goldstein_S2_Long, aes(x = t90, y = `Peak E. over Flue.`, colour = runif(1, 0, 1)))+geom_point(size = 1)+ylab(expression(E[p]/S[prompt]~' 10kev-10MeV ('~keV ~ cm^{2} ~ erg^{-1} ~ ', GBM)'))+xlab('t90 (s, GBM)')+geom_point(data = Goldstein_S2_Short, color = "grey")+scale_colour_gradient2(low = "black",mid ="black", high = "black",  midpoint = 0.5, name="Burst Types")+geom_point(data = Goldstein_S2_mergers, pch=4, color = "red")+geom_point(data = Goldstein_S2_collapsars, pch=8, color ='blue')+scale_y_log10(labels = trans_format("log10", math_format(10^.x)))+scale_x_log10(labels = trans_format("log10", math_format(10^.x)))
plot(NULL ,xaxt='n',yaxt='n',bty='n',ylab='',xlab='', xlim=0:1, ylim=0:1)
legend("topleft", title='Burst Types', legend = c('Unknown Long', 'Unknown Short', "Mergers", 'Collapsars'), col = c('black', 'grey', 'red', 'blue'), pch = c(20, 20, 4, 8))
##
missing<-which(!complete.cases(Goldstein_S2_Data))
no_NA_Goldstein_S2_Data<- Goldstein_S2_Data[-missing, ]
collapsar_mask<-no_NA_Goldstein_S2_Data$Name %in% Collapsars
merger_mask<-no_NA_Goldstein_S2_Data$Name %in% Mergers
# short_list<-which(no_NA_Goldstein_S2_Data$t90<4.2)
# long_list<-which(no_NA_Goldstein_S2_Data$t90>4.2)
Classification<-rep("Unknown", nrow(no_NA_Goldstein_S2_Data))
# Classification[short_list]<-"merger"
# Classification[long_list]<-"collapsar" 
Classification[collapsar_mask]<-"collapsar"
Classification[merger_mask]<-"merger"
temp_Goldstein_S2_Data<-data.frame(cbind(no_NA_Goldstein_S2_Data$Name, log10(no_NA_Goldstein_S2_Data$`Peak E. over Flue.`), log10(no_NA_Goldstein_S2_Data$E_P_Over_S_Err), log10(no_NA_Goldstein_S2_Data$t90), log10(no_NA_Goldstein_S2_Data$t90_err), log10(no_NA_Goldstein_S2_Data$Peak_E), log10(no_NA_Goldstein_S2_Data$Peak_E_Err), log10(no_NA_Goldstein_S2_Data$Fluence), log10(no_NA_Goldstein_S2_Data$Fluence_Err), Classification))
colnames(temp_Goldstein_S2_Data)<-c("Name", "Peak_E_over_Flu", "E_P_Over_S_Err", "t90", "t90_err", "Peak_E", "Peak_E_Err", "Fluence", "Fluence_Err", "Classification.")
write.csv(temp_Goldstein_S2_Data, file.path(path, "Goldstein_Full_DataSet_W_Name.csv"))
new_Goldstein_S2_Data<-data.frame(cbind(log10(no_NA_Goldstein_S2_Data$`Peak E. over Flue.`), log10(no_NA_Goldstein_S2_Data$t90), as.factor(Classification)))
colnames(new_Goldstein_S2_Data)<-c("Peak_E_over_Flu", "t90", "as.factor.Classification.")
# model <- randomForest(formula = no_NA_H_2b_Data$Classification ~ ., data = no_NA_H_2b_Data)
unknown_remover<-which(new_Goldstein_S2_Data$as.factor.Classification.==3)
merger_mask<-which(new_Goldstein_S2_Data$as.factor.Classification.==2)
collapsar_mask<-which(new_Goldstein_S2_Data$as.factor.Classification.==1)
training_set=new_Goldstein_S2_Data[-unknown_remover, ]
svmfit<-svm(training_set$as.factor.Classification. ~ ., data = training_set, type = "C-classification", cost = 1.0, kernel = "sigmoid", probability=TRUE)
training_set_2<-data.frame(training_set)
colnames(training_set_2)<-c("Peak_E_over_Flu", "t90", "Classification.")
write.csv(training_set_2, file.path(path, "Goldstein_Training_Set.csv"))
print(svmfit)
plot(svmfit, training_set, Peak_E_over_Flu~t90, ylab=expression(E[p]/S[prompt]~' 10kev-10MeV ('~erg ~ cm^{2} ~ erg^{-1} ~ ', GBM)'), xlab='t90 (s, GBM)', log="xy")
# points(log10(Goldstein_S2_unknown$t90), log10(Goldstein_S2_unknown$`Peak E. over Flue.`))
predicted_svm<-predict(svmfit, new_Goldstein_S2_Data[unknown_remover, ], probability=TRUE)
new_table<-attr(predicted_svm, "probabilities")
new_table<-cbind(no_NA_Goldstein_S2_Data$Name, no_NA_Goldstein_S2_Data$t90, no_NA_Goldstein_S2_Data$`Peak E. over Flue.`, new_table)
colnames(new_table)<-c("Name", "t90", "E_P_Over_S", "P_collapsar", "P_merger")
new_table<-data.frame(new_table)
write.csv(new_table, file.path(path, "Goldstein_Classification.csv"))
colnames(Goldstein_S2_collapsars)<-c("Name", "Peak_E_over_Flu", "E_P_Over_S_Err", "`Hardness Ratio`", "t90", "t90_err")
new_Goldstein_S2_Data<-new_Goldstein_S2_Data;
new_Goldstein_S2_Data$Peak_E_over_Flu<-10^(new_Goldstein_S2_Data$Peak_E_over_Flu)
# new_Goldstein_S2_Data$E_P_Over_S_Err<-10^(new_Goldstein_S2_Data$E_P_Over_S_Err)
new_Goldstein_S2_Data$t90<-10^(new_Goldstein_S2_Data$t90)
# new_Goldstein_S2_Data$t90_err<-10^(new_Goldstein_S2_Data$t90_err)
new_Goldstein_S2_collapsars<-Goldstein_S2_collapsars;
# new_Goldstein_S2_collapsars$Peak_E_over_Flu<-log10(new_Goldstein_S2_collapsars$Peak_E_over_Flu)
# new_Goldstein_S2_collapsars$E_P_Over_S_Err<-log10(new_Goldstein_S2_collapsars$E_P_Over_S_Err)
# new_Goldstein_S2_collapsars$t90<-log10(new_Goldstein_S2_collapsars$t90)
# new_Goldstein_S2_collapsars$t90_err<-log10(new_Goldstein_S2_collapsars$t90_err)
colnames(Goldstein_S2_mergers)<-c("Name", "Peak_E_over_Flu", "E_P_Over_S_Err", "`Hardness Ratio`", "t90", "t90_err")
new_Goldstein_S2_mergers<-Goldstein_S2_mergers;
# new_Goldstein_S2_mergers$Peak_E_over_Flu<-log10(new_Goldstein_S2_mergers$Peak_E_over_Flu)
# new_Goldstein_S2_mergers$E_P_Over_S_Err<-log10(new_Goldstein_S2_mergers$E_P_Over_S_Err)
# new_Goldstein_S2_mergers$t90<-log10(new_Goldstein_S2_mergers$t90)
# new_Goldstein_S2_mergers$t90_err<-log10(new_Goldstein_S2_mergers$t90_err)
ggplot(new_Goldstein_S2_Data[unknown_remover, ], aes(x = t90, y = Peak_E_over_Flu, colour = attr(predicted_svm, "probabilities")[,1])) +geom_point(size = 1)+ylab(expression(E[p]/S[prompt]~' 10kev-10MeV ('~keV ~ cm^{2} ~ erg^{-1} ~ ', GBM)'))+xlab('t90 (s, GBM)')+scale_colour_gradient2(low = "grey",mid =muted("blue"), high = "black",  midpoint = 0.5, name="Inferred Collapsar\n Probability")+geom_point(data = new_Goldstein_S2_mergers, color = "red")+geom_point(data = new_Goldstein_S2_collapsars, color = "cyan")+scale_y_log10(labels = trans_format("log10", math_format(10^.x)))+scale_x_log10(labels = trans_format("log10", math_format(10^.x)))
plot(NULL ,xaxt='n',yaxt='n',bty='n',ylab='',xlab='', xlim=0:1, ylim=0:1)
legend("topleft", title='Known Burst Types', legend = c('Detected Collapsar', 'Detected Merger'), col = c( 'cyan', 'red'),  pch = c(20, 20))
write.svm(svmfit, svm.file = "E_p_over_S-t90-classifier.svm", scale.file = "E_p_over_S-t90-classifier.scale")
# plot(new_Goldstein_S2_Data[unknown_remover, ]$Peak_E_over_Flu~new_Goldstein_S2_Data[unknown_remover, ]$t90, ylab=expression(E[p]/S[prompt]~' 10kev-10MeV ('~erg ~ cm^{2} ~ erg^{-1} ~ ', GBM)'), xlab='t90 (s, GBM)', col=attr(predicted_svm, "probabilities")[,1], pch=20)
# points(log10(Goldstein_S2_mergers$t90), log10(Goldstein_S2_mergers$`Peak E. over Flue.`), pch=4, col='#09622A')
# points(log10(Goldstein_S2_collapsars$t90), log10(Goldstein_S2_collapsars$`Peak E. over Flue.`), pch=8, col='blue')
# legend("bottomleft",
#        legend = c('Sorted Collapsars', 'Sorted Mergers', "Detected Mergers", 'Detected Collapsars'),
#        col = c('black', 'grey', 'red', 'cyan'),
#        pch = c(20, 20, 20, 20))
###
Goldstein_Sample_3_Data <- read_excel(file.path(path, "Goldstein_Sample_3_Data.xlsx"), col_types = c("skip", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
missing<-which(!complete.cases(Goldstein_Sample_3_Data))
no_NA_Goldstein_S3_Data<- Goldstein_Sample_3_Data[-missing, ]
collapsar_mask<-no_NA_Goldstein_S3_Data$Name %in% Collapsars
merger_mask<-no_NA_Goldstein_S3_Data$Name %in% Mergers
Classification<-rep("Unknown", nrow(no_NA_Goldstein_S3_Data))
Classification[collapsar_mask]<-"collapsar"
Classification[merger_mask]<-"merger"
no_NA_Goldstein_S3_Data<-data.frame(cbind(no_NA_Goldstein_S3_Data$Name, log10(no_NA_Goldstein_S3_Data$`Peak E. over Flue.`), log10(no_NA_Goldstein_S3_Data$E_P_Over_S_Err), log10(no_NA_Goldstein_S3_Data$`Hardness Ratio`), log10(no_NA_Goldstein_S3_Data$t90), log10(no_NA_Goldstein_S3_Data$t90_err), log10(no_NA_Goldstein_S3_Data$Peak_E), log10(no_NA_Goldstein_S3_Data$Peak_E_Err), log10(no_NA_Goldstein_S3_Data$Fluence), log10(no_NA_Goldstein_S3_Data$Fluence_Err), log10(no_NA_Goldstein_S3_Data$AG_fluence), log10(no_NA_Goldstein_S3_Data$AG_fluence_err), as.factor(Classification)))
colnames(no_NA_Goldstein_S3_Data)<-c("Name", "Peak_E_over_Flu", "E_P_Over_S_Err", "Hardness Ratio", "t90", "t90_err", "Peak_E", "Peak_E_err", "Fluence", "Fluence_Err", "AG_fluence", "AG_fluence_err", "Classification.")
# new_Goldstein_S3_Data <- no_NA_Goldstein_S3_Data[apply(no_NA_Goldstein_S3_Data> -19, 1, all),]
# temp_Goldstein_S3_Data<-data.frame(cbind(new_Goldstein_S3_Data$Name, new_Goldstein_S3_Data$`Peak E. over Flue.`, new_Goldstein_S3_Data$t90,new_Goldstein_S3_Data$Peak_E, new_Goldstein_S3_Data$Fluence, new_Goldstein_S3_Data$AG_fluence, new_Goldstein_S3_Data$as.factor.Classification.))
# colnames(temp_Goldstein_S3_Data)<-c("Name", "Peak_E_over_Flu", "t90",  "Peak_E", "Fluence", "AG_fluence", "Classification.")
write.csv(no_NA_Goldstein_S3_Data, file.path(path, "Goldstein_AG_Full_DataSet_W_Name.csv"))
#now let's try it on the overlapping sample with redshifts
Goldstein_S6_Data <- read_excel(file.path(path, "Goldstein_Sample_6_Data.xlsx"), col_types = c("skip", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
missing<-which(!complete.cases(Goldstein_S6_Data))
no_NA_Goldstein_S6_Data<- Goldstein_S6_Data[-missing, ]
collapsar_mask<-no_NA_Goldstein_S6_Data$Name %in% Collapsars
merger_mask<-no_NA_Goldstein_S6_Data$Name %in% Mergers
Classification<-rep("Unknown", nrow(no_NA_Goldstein_S6_Data))
Classification[collapsar_mask]<-"collapsar"
Classification[merger_mask]<-"merger"
temp_Goldstein_S6_Data<-data.frame(cbind(no_NA_Goldstein_S6_Data$Name, log10(no_NA_Goldstein_S6_Data$`Peak E. over Flue.`),  log10(no_NA_Goldstein_S6_Data$E_P_Over_S_Err), log10(no_NA_Goldstein_S6_Data$t90), log10(no_NA_Goldstein_S6_Data$t90_err), log10(no_NA_Goldstein_S6_Data$Peak_E), log10(no_NA_Goldstein_S6_Data$Peak_E_Err), log10(no_NA_Goldstein_S6_Data$Fluence), log10(no_NA_Goldstein_S6_Data$Fluence_Err), Classification, no_NA_Goldstein_S6_Data$Redshift))
colnames(temp_Goldstein_S6_Data)<-c("Name", "Peak_E_over_Flu", "E_P_Over_S_Err", "t90", "t90_err", "Peak_E", "Peak_E_Err", "Fluence", "Fluence_Err", "Classification.", "Redshift")
write.csv(temp_Goldstein_S6_Data, file.path(path, "Goldstein_Redshift_AG_Full_DataSet_W_Name.csv"))
# new_Goldstein_S6_Data<-data.frame(cbind(log10(no_NA_Goldstein_S6_Data$`Peak E. over Flue.`), log10(no_NA_Goldstein_S6_Data$t90), as.factor(Classification)))
# colnames(new_Goldstein_S6_Data)<-c("Peak_E_over_Flu", "t90", "as.factor.Classification.")
# unknown_remover<-which(new_Goldstein_S6_Data$as.factor.Classification.==3)
# Second_predicted_svm<-predict(svmfit, new_Goldstein_S6_Data)
# plot(new_Goldstein_S6_Data$Peak_E_over_Flu~new_Goldstein_S6_Data$t90, ylab=expression(E[p]/S[prompt]~' 10kev-10MeV ('~erg ~ cm^{2} ~ erg^{-1} ~ ', GBM)'), xlab='t90 (s, GBM)', col=Second_predicted_svm, pch=20)
# svm_check=predict(svmfit, new_Goldstein_S6_Data[-unknown_remover, ])
# confusionMatrix(svm_check, factor(new_Goldstein_S6_Data[-unknown_remover, ]$as.factor.Classification.), dnn = c("Prediction", "Reference"))
```

This chunk is only interesting if you want to know what the classification looks like in 3D.
```{r lidol chunk on doing triple svms, echo=FALSE}
Goldstein_S2_Data <- read_excel(file.path(path, "Goldstein_Sample_2_Data.xlsx"),col_types = c("skip", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
#but now it's all worth importing
missing<-which(!complete.cases(Goldstein_S2_Data))
no_NA_Goldstein_S2_Data<- Goldstein_S2_Data[-missing, ]
collapsar_mask<-no_NA_Goldstein_S2_Data$Name %in% Collapsars
merger_mask<-no_NA_Goldstein_S2_Data$Name %in% Mergers
Classification<-rep("Unknown", nrow(no_NA_Goldstein_S2_Data))
Classification[collapsar_mask]<-"collapsar"
Classification[merger_mask]<-"merger"
new_Goldstein_S2_Data<-data.frame(cbind(log10(no_NA_Goldstein_S2_Data$Peak_E), log10(no_NA_Goldstein_S2_Data$Fluence), log10(no_NA_Goldstein_S2_Data$t90), as.factor(Classification)))
colnames(new_Goldstein_S2_Data)<-c("Peak_E", "Fluence", "t90", "as.factor.Classification.")
# new_Goldstein_S2_Data<-data.frame(cbind(log10(no_NA_Goldstein_S2_Data$`Peak E. over Flue.`), log10(no_NA_Goldstein_S2_Data$t90), as.factor(Classification)))
# colnames(new_Goldstein_S2_Data)<-c("Peak_E_over_Flu", "t90", "as.factor.Classification.")
unknown_remover<-which(new_Goldstein_S2_Data$as.factor.Classification.==3)
merger_mask<-which(new_Goldstein_S2_Data$as.factor.Classification.==2)
collapsar_mask<-which(new_Goldstein_S2_Data$as.factor.Classification.==1)
training_set=new_Goldstein_S2_Data[-unknown_remover, ]
svmfit<-svm(training_set$as.factor.Classification. ~ ., data = training_set, type = "C-classification", cost = 1.0, kernel = "sigmoid", probability=TRUE)
print(svmfit)
# Simulate some data
n    = 100
nnew = 50
set.seed(1729)
group = sample(2, n, replace=T)
dat   = data.frame(group=factor(group), matrix(rnorm(n*3, rep(group, each=3)), ncol=3, byrow=T))

# # Fit SVM
# fit = svm(group ~ ., data=dat)
# 
# # Plot original data
# plot3d(dat[,-1], col=dat$group)

# Get decision values for a new data grid
newdat.list = lapply(training_set, function(x) seq(min(x), max(x), len=nnew))
newdat      = expand.grid(newdat.list)
names(newdat) <- c("Peak_E", "Fluence", "t90")
# names(newdat) <- c("Peak_E_over_Flu", "t90")
newdat.pred = predict(svmfit, newdata=newdat, decision.values=T)
newdat.dv   = attr(newdat.pred, 'decision.values')
newdat.dv   = array(newdat.dv, dim=rep(nnew, 3))

# Fit/plot an isosurface to the decision boundary
# plot3d(x=new_Goldstein_S2_Data[unknown_remover,]$Peak_E, y=new_Goldstein_S2_Data[unknown_remover,]$fluence, z=new_Goldstein_S2_Data[unknown_remover,]$t90, ylab="Prompt Fluence, 10 keV-1 MeV (erg cm^-2, GBM)", xlab=paste(strwrap("Prompt Peak Energy, 10 keV-1 MeV keV, GBM)", width = 25), collapse = "\n"), zlab="t90 (s, GBM)")
# contour3d(newdat.dv, level=0, x=, y=newdat.list$fluence, z=newdat.list$t90, add=T)
#
predicted_svm<-predict(svmfit, new_Goldstein_S2_Data[unknown_remover, ], probability=TRUE)
predictions<-attr(predicted_svm, "probabilities")[,1]
temp_color<-diverging_hcl(length(predictions))[rank(predictions)]
plot3d(x=new_Goldstein_S2_Data[unknown_remover,]$Peak_E, y=new_Goldstein_S2_Data[unknown_remover,]$Fluence, z=new_Goldstein_S2_Data[unknown_remover,]$t90, ylab="Prompt Fluence, 10 keV-1 MeV (erg cm^-2, GBM)", xlab=paste(strwrap("Prompt Peak Energy, 10 keV-1 MeV (keV, GBM)", width = 25), collapse = "\n"), zlab="t90 (s, GBM)", col = temp_color)
contour3d(newdat.dv, level=0, x=newdat.list$Peak_E, y=newdat.list$Fluence, z=newdat.list$t90, add=T)

# non_Swift_redshifts <- read_excel("/Users/nnuessle/Documents/Work/burst_matching_algorithm/actual_paper/prompt-and-afterglow-matching/edited_non_Swift_redshifts.xlsx", col_types = c("skip", "skip", "skip", "skip", "text", "skip", "skip", "skip", "skip", "skip", "skip", "skip", "skip", "text"))
# #this is technically cheating but i honestly am too lazy to think up a better idea
# Bursts_with_z <- c(as.integer(gsub("GRB", "", non_Swift_redshifts$`GRB Name`))) #this removes every time it says "GRB" in a GRB name
# zs_of_bursts <- c(as.double(gsub("[^0-9.-]", "", non_Swift_redshifts$zc))) #and this removes anything non-numeric from the redshift, since I didn't remember seeing any pairs or ranges. There are a number of upper limits that will get lost though (I mean, the value is preserved, but the fact that it's an upper limit is not).
# new_redshifts<-no_NA_Goldstein_S2_Data$Name %in% Bursts_with_z
# new_bursts_with_z<-no_NA_Goldstein_S2_Data[new_redshifts, ]
# matched_zs=rep(0, nrow(new_bursts_with_z))
# for(i in 1:length(new_bursts_with_z)){
#   for(j in 1:length(Bursts_with_z)){
#     if(new_bursts_with_z$Name[i]==Bursts_with_z[j]){
#       matched_zs[i]=zs_of_bursts[j] #very inefficient, but it does work
#     }
#   }
# }
# new_bursts_with_z$Redshift<-matched_zs
# old_bursts_with_z<-no_NA_Goldstein_S6_Data #so here's all the ones matched using sweeft
# joint_bursts_with_z<-bind_rows(new_bursts_with_z, old_bursts_with_z) #and we glue them together
# length(unique(joint_bursts_with_z$Name)) == nrow(joint_bursts_with_z) #this just verifies that every burst isn't a repeat of any other one--you want it to return true
# new_joint_bursts_with_z<-data.frame(cbind(joint_bursts_with_z$Name, log10(joint_bursts_with_z$`Peak E. over Flue.`), log10(joint_bursts_with_z$E_P_Over_S_Err), log10(joint_bursts_with_z$`Hardness Ratio`), log10(joint_bursts_with_z$t90/(1+joint_bursts_with_z$Redshift)), log10(joint_bursts_with_z$t90_err), log10(joint_bursts_with_z$Peak_E/(1+joint_bursts_with_z$Redshift)), log10(joint_bursts_with_z$Peak_E_Err), log10(joint_bursts_with_z$Fluence), log10(joint_bursts_with_z$Fluence_Err), joint_bursts_with_z$Redshift))
# colnames(new_joint_bursts_with_z)<-c("Name", "Peak E. over Flue.", "E_P_Over_S_Err", "Hardness Ratio", "t90", "t90_err", "Peak_E", "Peak_E_err", "Fluence", "Fluence_Err", "Redshift")
# #And now we gotta do the actual triple svm, which is gonna be a pain and a half.
# # Get decision values for a new data grid
# newerdat.list = lapply(training_set, function(x) seq(min(x), max(x), len=nnew))
# newerdat      = expand.grid(newerdat.list)
# names(newerdat) <- c("Peak_E", "Fluence", "t90")
# # names(newdater) <- c("Peak_E_over_Flu", "t90")
# newerdat.pred = predict(svmfit, newdata=newerdat, decision.values=T)
# newerdat.dv   = attr(newerdat.pred, 'decision.values')
# newerdat.dv   = array(newerdat.dv, dim=rep(nnew, 3))
# predicted_svm_2<-predict(svmfit, new_joint_bursts_with_z, probability=TRUE)
# predictions_2<-attr(predicted_svm_2, "probabilities")[,1]
# temp_color_2<-diverging_hcl(length(predictions_2))[rank(predictions_2)]
# plot3d(x=new_joint_bursts_with_z$`Peak E. over Flue.`, y=new_joint_bursts_with_z$t90, z=new_joint_bursts_with_z$Redshift, ylab="t90 (s, GBM)", xlab=expression('Prompt Peak Energy over Fluence, 10 keV-1 MeV ('~keV ~ cm^{2}~ erg^{-1}~', GBM)'), zlab="Redshift, various", col = temp_color_2)
# contour3d(newdat.dv, level=0, x=newdat.list$Peak_E, y=newdat.list$Fluence, z=newdat.list$t90, add=T)
```